language: ruby
rvm: 2.3.1
jdk: oraclejdk8

install:
  - gem update --system
  - gem --version
  - bundle install
script:
  - jekyll build
  - htmlproofer ./_site --check-favicon
  - java -jar vnu.jar --skip-non-html _site/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
