language: ruby
rvm: 2.1
jdk: oraclejdk8

install: gem install jekyll html-proofer
script:
  - jekyll build
  - htmlproofer ./_site --check-html --check-favicon
  - java -jar vnu.jar --skip-non-html _site/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
