title: Blast Piruin Panichphol
email: piruin.p@gmail.com
description: >
  Piruin Panichphol or Blast is Thai Full-Stack Android developer,
  Scrum Master, Technical Coach. This is Piruin's personal blog.
url: "http://piruin.me"
logo: /image/logo.png

author: Blast Piruin Panichphol
twitter:
  username: Piruin
social:
  links:
    - https://github.com/piruin
    - https://twitter.com/piruin
    - https://www.facebook.com/piruin
    - https://www.instagram.com/blastpiruin/
    - https://www.linkedin.com/in/piruin

# Build settings
encoding: utf-8
timezone: Asia/Bangkok
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile*
  - vnu.jar

permalink: /blog/:title/

gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      language: "en"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      language: "en"
      layout: "default"
