title: Blast Piruin
email: piruin.p@gmail.com
description: Thai fullstack mobile developer who walking in path of software craftmanship.
url: "http://piruin.me"

exclude:
  - README.md
  - Gemfile*
  - vnu.jar

author: Blast Piruin Panichphol
twitter:
  username: Piruin
social:
  name: พิรุณ พานิชผล
  links:
    - https://github.com/piruin
    - https://twitter.com/piruin
    - https://www.facebook.com/piruin
    - https://www.instagram.com/blastpiruin/
    - https://www.linkedin.com/in/piruin

# Build settings
encoding: utf-8
timezone: Asia/Bangkok
markdown: kramdown
permalink: /blog/:title/

gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      language: "en"
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      language: "en"
      layout: "default"
